make the fmt step more clear

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -23,6 +23,12 @@ jobs:
       - name: Terraform Format
         id: fmt
         run: terraform fmt -check terraform
+        continue-on-error: true
+
+      - name: Tell the user that fmt failed
+        id: fmt-check
+        run: echo "terraform fmt failed, please make sure your .tf files are properly formatted before committing."; exit 1
+        if: steps.fmt.outcome == "failure"
 
       - name: Terraform Init
         id: init
